.circleci/config.yml
Build started failing because it cannot find the eslint command when running the deployment script. I think it is related to Circle CI's cache. I hope this will fix it.
Based on https://circleci.com/docs/2.0/caching/#clearing-cache
=> Add branch to Circle CI cache key

src/messaging/messaging-service-client.js
Introduced after [adding the code to prevent logs from development](https://github.com/Rise-Vision/chrome-os-player/pull/46/commits/ddc81f9a0330a244d5fd9834c15030ea275b986a). It affects the connection to messaging service when running on development.
=> Fix to machine id not being generated when running on development

app/manifest.json
I confirmed the `required_platform_version` was preventing the updates on uptime machines. This is how this feature works according to the [documentation](https://support.google.com/chrome/a/answer/3316168#expectbehaviour):
> Scenario: The required_platform_version value is lower than the device’s current platform version. Result: The app is installed but the device OS will not get updated unless the required_platform_version value is updated to a version higher than the current device OS version.
Note: The first time an app is pushed from the Chrome Web Store, the required_platform_version value is verified, but not compared to the device’s current platform version.
However there is this `always_update` flag that was created to overcome this limitation. This flag is not well documented …
=> Restore required_platform_version but adds the always update flag to enable app updates

src/window-manager.js, test/unit/window-manager.js
I think there's a race condition with setting/releasing the flag when the registration window is closed after viewer window is launched. 
I think the keep awake is only a requirement for viewer as registration requires user interaction so it is more likely that the display is not going to be idle enough to be turned off. Removing it will fix the race condition and keep awake should work fine for viewer.
=> Remove keep awake flag handling from registration window

src/storage/file-server.js
Tested on my Asus Chromebox and on Mac OS and Ubuntu
=> Add delay in set keep alive to fix HTTP server when running on Chrome OS

src/messaging/viewer-messaging.js, test/unit/messaging/viewer-messaging.js
Content wasn't showing up sometimes because `viewerMessaging.viewerCanReceiveContent()` was designed for a single caller and now it this method is used when sending content to viewer and when initializing licensing.
=> Fix viewer messaging to work with multiple callers

src/content-loader.js, src/display-registration/registration.js, src/viewer.js, test/unit/content-loader.js
- Moved fetch content to registration/countdown window
- Store content in local storage to avoid refetching it on viewer/player window
- Show display id screen with invalid display id message if content indicates that the display id is no longer valid (empty object is returned)
=> Show the invalid display screen when data indicates that display id is no longer valid

.circleci/config.yml, deploy.js
Required for chrome os player reliability since we only consider latest version in queries.
=> After store deploy, upload version string to GCS

src/display-registration/display-id.html
- Removed maxlength attribute from display id input to support legacy ids
=> Enable legacy id input

src/viewer.js
- Allow loadplugin and geolocation permissions
The same permissions are allowed in the [legacy player](https://github.com/Rise-Vision/player-chromeapp/blob/c0400d9b69d837a7bc16f77862fcfb3807c4ec29/app/js/app.js#L32).
=> Handle webview permission request

src/viewer.js
- Avoid logging the same error twice and allow other modules to be initialized
=> Catch MS connection error on init

src/reboot-scheduler.js, test/unit/reboot-scheduler.js
- Schedule an alarm that calls chrome.runtime.restart when chrome.runtime.restartAfterDelay is not available
=> Fix restart on old Chrome OS versions

.circleci/config.yml, src/content-comparison.js, src/content-loader.js, src/update-frequency-logger.js, test/unit/content-comparison.js, test/unit/content-loader.js
https://trello.com/c/IMMMbYBm/4558-3-chros-log-an-event-when-my-presentation-or-schedule-has-been-updated
Schedule and presentations are compared to determine if there are any changes to log. Comparison uses `changeDate` rather than a hash.
=> Add sched / pres change logging

src/viewer.js
- Add undocumented runAt option set to 'document_end' to `webview.executeScript` call hoping that it will avoid the timing issue where viewer executes its code before injection happens
I found this option mentioned in [this Stack Overflow answer](https://stackoverflow.com/a/26833386) and tried it first with 'document_start' but it didn't work because document.head was not ready yet so we can't inject the script element.
According to the [documentation](https://developer.chrome.com/extensions/content_scripts#run_time) and [Chrome's source code](https://cs.chromium.org/chromium/src/extensions/common/user_script.h?rcl=902482f96ca679f42c17c4abb1bedea401322f05&l=63), the default execution time is 'document_idle' which can happen later than content loads leading to the timing issue with viewer. …
=> Improve viewer injection

src/content-comparison.js, test/unit/content-comparison.js
Content comparison should expect content with no schedule object for
cases when the display is using the default schedule.
=> Handle default content json file with no schedule

src/storage/database/api.js, src/storage/database/lokijs/database.js, src/storage/expiration.js, src/storage/storage.js, test/unit/storage/storage.js
This is part of the fix for defect https://github.com/Rise-Vision/rise-launcher-electron/issues/757
As MS doesn't remove deleted entries on DELETE anymore, local storage should send a unwatch message to tell MS to remove files from watchlist and fileMetadata.
=> Unwatch expired files

src/viewer-injector.js
In some cases head is not available so documentElement (<html>) is used
for the script tag as a fallback.
TextContent is used since we're not providing HTML for the script
contents.
=> Use documentElement and textContent

src/window-manager.js, test/unit/window-manager.js
In chrome os 71 there is a slight difference in ordering of async
operations.
The createWebviewWindow promise resolves before the viewer window
DOMContentLoaded event. This results in the registration window being
closed due to the previousWindow.close() call and so the webview.src is
never set and viewer.risevision.com/Viewer.html is never loaded.
That in turn results in the script injection not firing because it is
waiting for loadCommit event.
@andrecardoso can you test this on a chrome 70 device? I tested it on my dev linux machine on chrome 70, and my chrome bit on chrome 71. I'm going to keep my device on 71.
=> Don't close reg window before setting webview src

src/storage/messaging/watch/watch.js
Without version metadata, whenever a watchlist is out of sync
(lastChanged does not match MS) the folder metadata entry will be
deleted. This is because MS sends version "0" for folders and
version "0" indicates MS-side deletion unless the version matches,
in which case the files are considered up to date and no deletion
will occur.
So without a version "0" for folder metadata, the folder version is
mismatched and a new folder-watch will be submitted to MS. This results
in a new set of tokens in the response and this will result in all
files being re-downloaded.
=> Store folder version metadata

src/storage/messaging/watch/watch.js, test/unit/storage/messaging/watch/watch.js
This was merged in local-storage-module here https://github.com/Rise-Vision/local-storage-module/pull/86 but it was missing on Chrome OS. It is required to fix https://github.com/Rise-Vision/rise-launcher-electron/issues/773
=> Do not override error message from MS

src/storage/messaging/watch/watch.js, src/storage/messaging/watch/watchlist.js, test/unit/storage/messaging/watch/watch.js, test/unit/storage/messaging/watch/watchlist.js
If a folder watch is submitted against a folder that doesn't exist on
GCS, MS doesn't record it in the watchlist as the error is returned
early.
But local-storage will record the folder in the file metadata.
This change ensures that any missing folders are resubmitted by
local-storage so that a new GCS check is triggered.
=> Resubmit WATCH for empty folders

src/content.js, src/messaging/viewer-messaging.js, test/unit/messaging/viewer-messaging.js
- Webview messaging requires the targe origin to be set as the loaded URL for security reasons. We were setting it only when init was called because the URL didn't change. With no viewer mode, we need to configure messaging everytime we load a new URL
=> Configure webview messaging on load url

src/storage/messaging/watch/watch.js, test/unit/storage/messaging/watch/watch.js
The second check for current version mismatch doesn't work in cases
where a watch is submitted for a file and then another watch is
submitted before the first watch has resulted in a completed download.
The first will update the version, and then the second will set
CURRENT even though the download isn't yet complete.
=> Set stale when MS provides token

src/content.js, src/scheduling/schedule-parser.js
Initially no-viewer mode was limited to Rise Storage urls based on a
specific target url. We need to enable more urls for widget staging
as well as other Rise Storage origins like commondatastore.googleapis.
Rather than a specific whitelist, we enable no-viewer for *any* urls.
There's no reason to load urls in Viewer.
=> Remove restriction to RiseStorage URLs for no-viewer

src/network-checks/index.js, src/uptime/network-investigation.js
This url is more inline with [documentation](https://help.risevision.com/hc/en-us/articles/115002459246-Rise-Player-network-requirements) while returning a smaller payload than the root url, and also being more to the point.
=> Update aws url

app/manifest.json
This is a test to help fixing the duplicate description that appears on Chrome Web Store
=> Add description field to manifest.json

src/display-registration/countdown.js, src/display-registration/online-waiting.html, src/network-checks/index.js, test/unit/display-registration/countdown.js
- No longer rely on window 'online' event
- Poll viewer URL when waiting for online status
- UI copy updated to be clear it is waiting on connecting to Rise
=> Change waiting for offline state

src/logging/bq-client.js
Inserting multiple entries with the same timestamp was failing, only one entry would be recorded.
Therefore, component uptime was being logged for only one of the components of a template.
Updated to follow electron implementation: https://github.com/Rise-Vision/rise-common-electron/blob/master/bq-client.js#L50.
@andrecardoso @alex-deaconu Please review. Thanks
=> Fix logging entries with the same timestamp

src/html-template-url-parser.js, test/unit/content-loader.js
Uses HTTPS for loading HTML Templates to allow Service Workers and Cache API to work.
@alex-deaconu @andrecardoso Please review. Thanks!
=> Uses HTTPS for loading HTML Templates

package-lock.json, package.json, src/html-template-url-parser.js, test/unit/content-loader.js
This is part of the fix for defect https://github.com/Rise-Vision/rise-vision-apps/issues/1208
Defect https://github.com/Rise-Vision/rise-vision-apps/issues/1208 happens because sometimes the template runs `RisePlayerConfiguration.configure()` before player has finished [injecting its code](https://github.com/Rise-Vision/chrome-os-player/blob/master/src/viewer-injector.js). In this case, the template behaves like in preview mode and the schedule gets stuck because play until done code doesn't run.
This PR adds a URL parameter called `waitForPlayer` that `common-template` will read and wait for injected code to be ready before finishing configuration.
This needs to be tested in conjunction with the changes in `common-template`. It was tested running player locally and having …
=> Add wait for player url parameter

src/network-checks/index.js, test/unit/network-checks/index.js
Fix delay when player is waiting for viewer when started offline
Player is not delaying when retrying check for viewer when started offline. 
Unit and manual tests
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
=> Fix delay when waiting for viewer

src/scheduling/schedule-player.js
Clear timeout in `playItems()` to avoid unnecessary `playItems()` calls. 
Every time "content-update" message is received and noViewerSchedulePlayer.start() is called, it initiates a new timer loop for the playItems() method.
Example: when content is loaded first time time, the playItems() is called once a second, then on the next "content-update" it is called twice a second and so on.
The same [fix was applied to the Player Electron](https://github.com/Rise-Vision/rise-player-electron/pull/120), so the second motivation is to keep Chrome OS Player code in sync with Player Electron.
Tested manually using Chrome inspector.
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has …
=> Clear timeout in playItems() to avoid unnecessary playItems() calls

src/content.js, src/messaging/viewer-messaging.js, test/unit/messaging/viewer-messaging.js
Fix for https://github.com/Rise-Vision/html-template-library/issues/668.
The main reason why the Google Slides template was showing black screen is that in some case `common-template` requested attribute data before storage module loaded, so it was a timing issue. This problem is resolved by ensuring that `fetchContent()` is called after `storage.init()`.
This PR also fixes another problem with Player when it starts in no-Viewer mode.  In that case `viewerCanReceiveContent()` blocked Player's initialization sequence. The caused the following problems: 
1) Player never called `submitWatchForProductAuthChanges` i.e. it didn't register watch for product authorization changes.
2) Player had errors from which it could not recover during scheduled restart (see "USE CASE 1" on [this …
=> Fix for issue 668

src/storage/messaging/watch/watchlist.js, test/unit/storage/messaging/watch/watchlist.js
Mark local files and folders when server watchlist is empty and last changed is 0
This is to force refreshing local files when messaging service watchlist is empty when data is lost on the server causing issues such as https://github.com/Rise-Vision/rise-launcher-electron/issues/832
Tested locally using stage environment by deleting the watchlist and last changed manually from redis
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
If any Release Checklist …
=> Handle empty watchlist

src/scheduling/schedule-player.js, test/unit/scheduling/schedule-player.js
Change scheduling code to restart the current playing item on `content-update` event
Why is this change required? What problem does it solve?
Fix issue where template is not reloaded when single item schedule is saved: https://github.com/Rise-Vision/rise-slides/issues/32
Tested on staging using this schedule: https://apps-stage-0.risevision.com/schedules/details/47aadac8-cde4-4ac4-a5c4-67d7fb7a5d5f?cid=b258739a-527b-438c-b6ec-01057cecdfa2
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release …
=> Restart playing item on content-update when in no-viewer mode

src/content.js, src/network-checks/index.js, src/uptime/network-investigation.js, test/unit/content.js
Load Viewer from `https://widgets.risevision.com/viewer/Viewer.html` 
Origin consolidation
Tested locally via installing as unpackaged app extension
Validated viewer correctly loaded from right location and validated content with this schedule https://apps.risevision.com/schedules/details/822cbbd2-ad76-44c1-acc6-cff355e1c133?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f which contains 2 random templates and a legacy presentation containing a few different widgets. 
**PENDING**
Test legacy presentation containing gadgets, which is dependent on fixing `makeRequest` when Viewer loaded from widgets.risevision.com. 
- Update and deploy Viewer to fix `makeRequest` when loaded from widgets.risevision.com
- Deploy to lesser used version in App Store
- Deploy to widely used version in App Store
none
=> Update to load Viewer from widgets.risevision.com

README.md, app/manifest.json
Relax platform restriction to allow upgrade to version 81.
Requested by Alan.  See https://trello.com/c/Vf08UFUt/6557-chrome-player-allows-chrome-os-to-upgrade-to-chrome-version-81
No code change.
Will confirm upgrade on uptime.
- 100%
=> Relax max version restriction
