- app/css/player.css
- app/player.html
- src/display-id-screen.js
- src/display-id-validator.js
- src/player.js
- test/unit/display-id-screen.js
- test/unit/display-id-validator.js
- webpack.config.js
> Validate display ID

- docs/issue_template.md
@andrecardoso please review and merge if good w/ you. Thanks
> Issue template.

- deploy.js
- src/background.js
- src/window-manager.js
- test/unit/background.js
- test/unit/window-manager.js
Changed it to request keep awake as soon as the app is launched and release it when either player or viewer is closed
> Fix keep awake

- src/content-loader.js
- src/gcs-client.js
- src/viewer-injector.js
- src/viewer-message-handler.js
- src/viewer.js
- test/unit/content-loader.js
- test/unit/display-id-validator.js
- test/unit/gcs-client.js
- test/unit/viewer-message-handler.js
It takes [20 seconds](https://github.com/Rise-Vision/viewer/blob/master/src-js/Viewer/LocalMessaging.js#L5) to load content due to [viewer waiting for local messaging socket connection](https://github.com/Rise-Vision/viewer/blob/master/src-js/Viewer/EntryPoint.js#L98), but it is now loading the content again
> Fetch content json

- src/file-system.js
- test/unit/file-system.js
> Add file system object

- package-lock.json
- package.json
- src/logging/logger.js
- test/unit/logging/logger.js
I verified the issue is happening.
@tejohnso caught it here: https://github.com/Rise-Vision/chrome-os-player/pull/14#discussion_r172176048
> Fix to duplicate player config logs

- .circleci/config.yml
Last change didn't fix the problem. I think I got it now. The deploy task should depend on test so that the cache is ready for it.
> Change Circle CI workflow to be sequential

- src/storage/file-server.js
- src/viewer.js
- test/unit/storage/file-server.js
This is the first PR related to the http server
> Add empty http server

- src/storage/file-downloader.js
- src/storage/file-server.js
- src/storage/file-system.js
- src/viewer.js
- test/unit/storage/file-server.js
This enables us to serve large files without loading the whole file in memory
> File server serving files in chunks

- src/licensing/licensing.js
- src/messaging/viewer-messaging.js
- src/storage/messaging/local-messaging-helper.js
- src/viewer.js
- test/unit/licensing/licensing.js
- test/unit/messaging/viewer-messaging.js
- test/unit/storage/messaging/local-messaging-helper.js
Manually tested with image widget 1.0.0
> Add shell licensing module to make widgets work when using RLS

- package-lock.json
- package.json
- src/logging/logger.js
- test/unit/logging/logger.js
Porting [this PR](https://github.com/Rise-Vision/rise-player-electron/pull/61) over to Chrome OS.
> Log timezone to BigQuery

- src/reboot-scheduler.js
- src/viewer.js
- test/unit/reboot-scheduler.js
@Rise-Vision/delivery please review.
> Handle restart message

- src/storage/download-queue.js
- test/unit/storage/download-queue.js
This is the same fix [we applied to local storage module](https://github.com/Rise-Vision/local-storage-module/pull/81).
> Avoid downloading the same file repeatedly

- src/storage/messaging/watch/watchlist.js
Ported from electron player https://github.com/Rise-Vision/local-storage-module/pull/94
> A file might be in the watchlist db but not in the fileMetadata db yet.

- src/content-loader.js
- test/unit/content-loader.js
This is not the only problem, but it is causing presentations not being updated.
> Clear cached content after it gets loaded

- src/window-manager.js
- test/unit/window-manager.js
This way the window always starts fullscreen.
> Don't store window state

- src/messaging/messaging-service-client.js
- src/storage/file-system.js
- src/storage/messaging/watch/watch.js
This is to help us debugging https://trello.com/c/Y6iFTa1V/4527-chros-ms-not-responding
> Improve logs

- src/storage/database/lokijs/database.js
- Do not update folder entries
- Fix db update call
> Fix sync database with file system

- src/storage/file-system.js
- test/unit/storage/file-system.js
I found this issue in the logs
> Fix to removing cached file

- src/display-registration/claim-id-submittor.js
- src/display-registration/display-registration.js
- Accept lower and mixed case claim IDs
- Do not show previous content when display is configured with claim id
> Claim ID fixes

- app/css/webview.css
- app/webview.html
- src/display-registration/countdown.js
- src/display-registration/display-registration.js
- src/window-manager.js
- Makes it possible to close web view windows on fullscreen
> Add close button to webview window

- src/display-registration/claim-id.html
- src/display-registration/countdown.html
- src/display-registration/display-id.html
> Fix documentation link for installing chrome os

- src/content-loader.js
- test/unit/content-loader.js
- Add missing widgets that are now deployed to widgets.risevision.com
> Rewrite widgets URL

- src/display-registration/registration.js
- src/launch-environment.js
- src/viewer.js
- Fixes a problem where displays are not rebooting
> Persist launch data to be used on different webpack bundles

- src/background.js
- src/network-checks/index.js
- test/unit/background.js
@andrecardoso I've set up a `network-checks` feature branch for us. 
This PR is a starting point for my on-install part.
> Initial setup for network checks

- src/display-registration/display-id.html
- src/display-registration/display-registration.js
This way we don't suggest that the user view their displays when they have a network problem. We suggest they check network requirements.
> Network check error message

- app/css/player.css
- src/display-registration/countdown.html
- src/display-registration/countdown.js
- src/display-registration/display-registration.js
- src/network-checks/index.js
- test/unit/display-registration/countdown.js
- test/unit/display-registration/display-registration.js
- complete the basic countdown
- if network checks incomplete
- show waiting error message with countdown until network check abort (60s max)
- if no network failures
- launch viewer
- if network tests failed
- show error message with another 60s countdown
- launch viewer
> Show error during countdown

- .circleci/config.yml
- .gitignore
- deploy.js
- Publish different version for beta and production to GCS
- Change script to generate zip file and wait for manual publishing it and finally publish the version to GCS
> Change production deployment

- .eslintrc.json
- src/display-registration/display-registration.js
- src/network-checks/index.js
If a network error occurs the user can launch viewer anyway.
> Allow continue anyway on display id screen

- app/manifest.json
- This is the version when fetch API was released
> Set minimum Chrome version to 42

- src/licensing/index.js
- src/util.js
- src/viewer.js
- Handle NOEXIST message to notify authorization status listeners and fix client info log
> Add listener notification when not licensed

- src/storage/messaging/messaging.js
> Added logs when RLS files are added/deleted/updated

- src/reboot-scheduler.js
- test/unit/reboot-scheduler.js
- Scheduled reboot is not working sometimes. This commit changes it to always use chrome.alarms to see if that fixes the issue.
> Change reboot to use alarms

- src/content-comparison.js
- test/unit/content-comparison.js
> Handle valid content.json file with no presentations

- src/viewer.js
See https://stackoverflow.com/questions/26832848/chrome-apps-webview-tag-how-to-inject-css-or-js-in-time
https://trello.com/c/o8dMjtWz
> Inject scripts before page scripts run

- src/gcs-client.js
- src/viewer.js
- Increase retry number and timeout
- Reboot display when retry exhausted
> Improve content fetch retry

- app/css/player.css
> Highlight buttons and links

- src/uptime/renderer-health.js
- src/uptime/uptime.js
- src/viewer.js
- test/unit/uptime/renderer-health.js
- Leverage uptime renderer health check and restart the player when renderer fails 3 times in sequence
> Restart when renderer fails

- src/marketwall/display-id-server.js
- Check if socket is still connected before sending response
> Improve marketwall display id server

- src/licensing/store.js
- This is to avoid having multiple displays hitting the server at exact same time
> Add random variance to licensing repeat intervals

- src/marketwall/display-id-server.js
- Avoid net::SOCKET_NOT_CONNECTED errors
> Check error before send display id

- src/content-loader.js
- test/unit/content-loader.js
- HTML template presentations have no layout property. This was causing an error when it tried to replace URLs
> Fix content loader to support HTML templates

- src/storage/file-server.js
- test/unit/storage/file-server.js
- Allow requests from any domain
> Local file server responds with CORS headers

- src/content.js
- src/licensing/index.js
- Simplify authorization status listener
- Do not notify listener and send menssage when status is empty
> Fix licensing status toggling

- src/content.js
- Reload only when is top level
> Fix webview reload

- src/display-registration/countdown.js
- src/display-registration/online-waiting.html
- src/network-checks/index.js
- test/unit/display-registration/countdown.js
- Check if network is online at startup
- Show network error countdown screen
- Restart player after countdown
> Check for network connection at startup

- src/html-template-url-parser.js
- test/unit/content-loader.js
- Load HTML Templates on HTTP to avoid CORS issues and broken presentations when running on Viewer
> Fix HTML Templates on Viewer

- src/content-loader.js
- src/html-template-url-parser.js
- src/licensing/store.js
- src/logging/system-info.js
- src/messaging/messaging-service-client.js
- test/unit/content-loader.js
- test/unit/html-template-url-parser.js
- test/unit/licensing/licensing.js
- test/unit/logging/system-info.js
- test/unit/messaging/messaging-service-client.js
Read environment setting and configure player to stage:
- Connects to Messaging Service stage URL
- Connects to Store server stage URL
- Loads HTML templates from staging, otherwise loads from production (even when player is beta)
Designers need to test templates from staging
Manually tested locally. Unit tests added.
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
If any Release Checklist items were intentionally skipped, please provide which ones and …
> Read environment setting

- src/content.js
- src/messaging/clear-local-storage-request.js
Add `clear-local-storage-request` command handler. See [design doc](https://docs.google.com/document/d/1v1-IJMKvSqSQ3picvYycLpZwYAQIJqO8TQb5_vwUkHA/edit?usp=sharing).
This improvement was requested in Development Roadmap. It should also help with resolving the "stale content" issues (see [#832](https://github.com/Rise-Vision/rise-launcher-electron/issues/832) and [#829](https://github.com/Rise-Vision/rise-launcher-electron/issues/829)) if they ever occur.
Related PR: https://github.com/Rise-Vision/messaging-service/pull/83
Tested manually on stage.
- As the Reviewer, upon approving the changes in this PR, I …
> Add a command to clear Local Storage

- package-lock.json
Update dependencies
Why is this change required? What problem does it solve?
Fix security vulnerabilities 
Tested locally
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why
> Update lodash dependency to fix vulnerabilities
